common_ports:
  api_port: &api_port 7777
  frontend_port: &frontend_port 3000
  database_port: &database_port 3360
  proxy_port: &proxy_port 4000

api:
  port: *api_port
  debug: true
  endpoints:
    - path: /v1/status
      method: GET
    - path: /v1/users
      method: POST

frontend:
  port: *frontend_port
  enable_https: false
  domains:
    - example.com
    - api.example.com

database:
  host: postgres
  port: *database_port
  username: admin
  password: secret
  replicas:
    - host: replica1
      port: 5433
    - host: replica2
      port: 5434

proxy:
  host: nginx
  port: *proxy_port
  ssl: true
  upstreams:
    - host: api
      port: 8000
    - host: frontend
      port: 4000
